#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 246800-web-01 35.153.16.3 check port 80
        server 246800-web-02 54.160.79.86 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
