#!/usr/bin/env bash
# Bash script that displays `To infinity and beyond` indefinitely With a `sleep 2`

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done

